#!/bin/env bash
DEPENDS=(node npm)
BUILD_TOOL="yo"

_pre_bootstrap() {
    for DEP in $DEPENDS; do
        which $DEP >> /dev/null
        if [ $? -ne 0]; then
            echo "Please install '$DEP' in order to proceed" >> /dev/stderr
            return -1
        fi
    done
    return 0
}

_bootstrap() {

}

_post_bootstrap() {
    unset BUILD_TOOL
    return 0
}


