#!/bin/env bash
# addproj - Add a project to .projcs with the help of sed
IAMAT=$(dirname $0)
source $IAMAT/base
source $IAMAT/crossplat

addproj() {
    ALIAS=$1
    PROJECT=$2
    read -r -d '' SEDSTR << EOC
/^declare/{
n
i\name_alias[$ALIAS]="$PROJECT"
}
EOC
    sed_f -i "$SEDSTR" $PROJ_FILE
}

delproj() {
    ALIAS=$1
    SEDSTR="/\[$ALIAS\]/d"
    sed_f -i $SEDSTR $PROJ_FILE
}

proj-ls () {
    read -r -d '' SEDSTR << EOC
    1,2 d
/^declare/{
    c\alias\tproject
}
/^name_alias/{
s/name_alias//
s/"//g
s/=/\t/
}
EOC
    sed_f $SEDSTR $PROJ_FILE | awk '{ printf "%-20s %s\n", $1, $2 }'
}
