#!/usr/bin/env bash
# feature-switch - Turn features on/off
IAMAT=$(dirname $0)
source $IAMAT/base
source $IAMAT/crossplat

skf-turn-on() {
  SEDSTR="/#\!/a source $SWISSKNIFE_HOME\/$1"
  sed_f -i "$SEDSTR" $IAMAT/tools
}

skf-turn-off() {
  SEDSTR="/\\/$1$/d"
  sed_f -i $SEDSTR $IAMAT/tools
}

skf-show() {
  echo "Installed tools"
  awk -F '/' 'NR>1 { print "  "$NF }' $IAMAT/tools
}

skf-add-hook() {
  source $IAMAT/installed-hooks
  source $IAMAT/hooks/$1

  echo '' > $IAMAT/installed-hooks

  typeset -p  > $IAMAT/installed-hooks

}
