#!/bin/bash
IAMAT=$(dirname $0)
source $IAMAT/base
source $IAMAT/sd
source $IAMAT/addproj


mkproj() {
    PROJ_NAME=$1

    if [ -z "$2" ]; then
        PROJ_ALIAS=$2
    fi

    sd
    mkdir $PROJ_NAME
    
    if [ -z "$PROJ_ALIAS" ]; then
        addproj $PROJ_NAME $PROJ_ALIAS
    fi

    sd $PROJ_NAME

}

