#!/bin/env bash
IAMAT=$(dirname $0)
source $IAMAT/base
source $IAMAT/installed-hooks


sd () {
  # Exec pre hooks
  for HOOK in $PRE_SD_HOOKS; do
    eval _pre_sd_${HOOK}_hook
  done

  # Find matching target
  if [ -z "$1" ]; then

    # Go to home if none
    pushd $PROJ_DIR > /dev/null

  elif [ ! -d "$PROJ_DIR/$1" ]; then

    # Target not found, looking for aliases
    if [ -e "$PROJ_FILE" ]; then
      source $PROJ_FILE
    else
      echo "Unable to find '.projcd' alias file" >> /dev/stderr
      return -1
    fi

    [ ${name_alias[$1]+1} ] && TGT=${name_alias[$1]} || (echo "Alias not found" >> /dev/stderr && return -1)
  else
    TGT=$1
  fi

  # Check if target exists
  if [ ! -e "$PROJ_DIR/$TGT" ]; then; echo "Target directory not found" >> /dev/stderr && return -1; fi

  # Force directory change
  pushd $PROJ_DIR/$TGT > /dev/null

  for HOOK in $POST_SD_HOOKS; do
    eval _post_sd_${HOOK}_hook
  done

  unset TGT
  unset IAMAT

  return 0
}
